### PR TITLE
Update from skeleton

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR updates this lost sheep to integrate our glorious [cisagov/action-lineage](https://github.com/cisagov/action-lineage) automated update system. This includes bringing the testing up-to-date and migrating from TravisCI to GitHub Actions for the CI pipeline.

## 💭 Motivation and Context ##

This repository is used by other repositories that have been brought up-to-date, so it should also be up-to-date. Also, no repository left behind.

## 🧪 Testing ##

Automated testing passes.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
Great work bringing this one into the light!  I have two minor changes to request:
1. Shouldn't `molecule.yml` be a symlink to `molecule-no-systemd.yml` instead?
2. If all the platforms in `molecule-no-systemd.yml` pass then we should update `meta/main.yml` accordingly.

**Comment by mcdonnnj** [comment]
> 
> 
> Great work bringing this one into the light! I have two minor changes to request:
> 
>     1. Shouldn't `molecule.yml` be a symlink to `molecule-no-systemd.yml` instead?
> 
>     2. If all the platforms in `molecule-no-systemd.yml` pass then we should update `meta/main.yml` accordingly.

You were right about which configuration `molecule.yml` should symlink to for this project. I had `systemd` on the brain and misread `sysctl` as `systemctl` when I was updating everything. Please see 643e478 for the change.

Unless I am missing something the `meta/main.yml` should now have all platforms in it since tests pass.

**Review by dav3r — APPROVED** [review]
This looks great to me- thanks for wrangling this stray! 🏇

**Review by jsf9k — APPROVED** [review]
Thanks for fixing the `molecule.yml` symlink.  You're right about `meta/main.yml`.  I must have been looking at the develop branch or something else.  Or I was sundowning.

**Pull request merged**
